/* AUTO-GENERATED FILE.  DO NOT MODIFY.
 *
 * This class was automatically generated by the
 * aapt tool from the resource data it found.  It
 * should not be modified by hand.
 */

package com.khf.inferno.sylab;

public final class R {
    public static final class attr {
    }
    public static final class dimen {
        public static final int activity_horizontal_margin=0x7f040000;
        public static final int activity_vertical_margin=0x7f040001;
    }
    public static final class drawable {
        public static final int ceglogo=0x7f020000;
        public static final int fb=0x7f020001;
        public static final int github=0x7f020002;
        public static final int home=0x7f020003;
        public static final int launch=0x7f020004;
        public static final int logo=0x7f020005;
        public static final int refresh=0x7f020006;
        public static final int splash=0x7f020007;
        public static final int sylab=0x7f020008;
    }
    public static final class id {
        public static final int aboutView=0x7f070000;
        public static final int alias=0x7f070010;
        public static final int appname=0x7f070003;
        public static final int content_frame=0x7f070007;
        public static final int cs=0x7f07000a;
        public static final int drawer_layout=0x7f070006;
        public static final int home=0x7f070002;
        public static final int imageView2=0x7f070009;
        public static final int imageView3=0x7f070014;
        public static final int lblListHeader=0x7f070011;
        public static final int lblListItem=0x7f070012;
        public static final int lvExp=0x7f070008;
        public static final int name=0x7f07000e;
        public static final int open_btn=0x7f070005;
        public static final int pdfView=0x7f07000d;
        public static final int photo=0x7f07000f;
        public static final int refresh_btn=0x7f070004;
        public static final int s1=0x7f070001;
        public static final int s9=0x7f070013;
        public static final int textView=0x7f07000b;
        public static final int textView16=0x7f070015;
        public static final int textView17=0x7f070016;
        public static final int textView2=0x7f07000c;
    }
    public static final class layout {
        public static final int about=0x7f030000;
        public static final int activity_navigation=0x7f030001;
        public static final int activity_splash=0x7f030002;
        public static final int comingsoon=0x7f030003;
        public static final int fragment_display=0x7f030004;
        public static final int list_about=0x7f030005;
        public static final int list_about_section=0x7f030006;
        public static final int list_group=0x7f030007;
        public static final int list_item=0x7f030008;
        public static final int third=0x7f030009;
    }
    public static final class string {
        public static final int action_settings=0x7f050000;
        public static final int alias_faizaan=0x7f050001;
        public static final int alias_harish=0x7f050002;
        public static final int alias_karthi=0x7f050003;
        public static final int app_name=0x7f050004;
        public static final int aulisius=0x7f050005;
        public static final int code=0x7f050006;
        public static final int developer=0x7f050007;
        public static final int error=0x7f050008;
        public static final int license=0x7f050009;
        public static final int mac=0x7f05000a;
        public static final int pdfView=0x7f05000b;
        public static final int ranguski=0x7f05000c;
        public static final int roboto=0x7f05000d;
        public static final int title_activity_about=0x7f05000e;
        public static final int title_activity_splash=0x7f05000f;
        public static final int version=0x7f050010;
    }
    public static final class style {
        /** 
            Theme customizations available in newer API levels can go in
            res/values-vXX/styles.xml, while customizations related to
            backward-compatibility can go here.
        
         */
        public static final int AppBaseTheme=0x7f060000;
    }
}
